kj-49/trail-volt

firmware/lib/u8g2.X/nbproject/private/private.xml, firmware/src/adc.c, firmware/src/configuration.h, firmware/src/nbproject/private/private.xml, firmware/src/sensors.c, firmware/src/sensors.h
=> Calibrate adc values to a vref of 2.5V

firmware/lib/u8g2.X/nbproject/private/private.xml, firmware/src/display.c, firmware/src/display.h, firmware/src/main.c, firmware/src/nbproject/configurations.xml, firmware/src/nbproject/private/private.xml, firmware/src/power.c, firmware/src/power.h, firmware/src/state.c, firmware/src/state.h
=> Add fsm skeleton with global state

firmware/src/controller/batteries.cpp, firmware/src/controller/batteries.h, firmware/src/controller/controller.ino, firmware/src/controller/display.cpp, firmware/src/controller/gpio.cpp, firmware/src/controller/gpio.h, firmware/src/controller/power.cpp, firmware/src/controller/power.h, firmware/src/controller/sensors.cpp, firmware/src/controller/sensors.h, firmware/src/controller/state.h
=> Add cell balancing

firmware/src/controller/adc.cpp, firmware/src/controller/adc.h, firmware/src/controller/batteries.cpp, firmware/src/controller/batteries.h, firmware/src/controller/charging.cpp, firmware/src/controller/charging.h, firmware/src/controller/controller.ino, firmware/src/controller/display.cpp, firmware/src/controller/display.h, firmware/src/controller/gpio.h, firmware/src/controller/state.cpp, firmware/src/controller/state.h
=> Vary duty cycle based on the supply voltage feedback

firmware/src/controller/batteries.cpp, firmware/src/controller/batteries.h, firmware/src/controller/charging.cpp, firmware/src/controller/charging.h, firmware/src/controller/controller.ino, firmware/src/controller/display.cpp, firmware/src/controller/state.h
=> Rework fsm flow and add balancing state

firmware/src/controller/charging.cpp, firmware/src/controller/charging.h
=> Implement logarithmic algorithm for improved duty cycle adjustment speed

firmware/src/controller/charging.cpp, firmware/src/controller/gpio.cpp, firmware/src/controller/gpio.h
=> Add shutdown pin support

firmware/src/controller/battery.cpp, firmware/src/controller/battery.h, firmware/src/controller/charging.cpp, firmware/src/controller/display.cpp, firmware/src/controller/gpio.cpp, firmware/src/controller/gpio.h, firmware/src/controller/temperature.cpp, firmware/src/controller/temperature.h
=> Update pinout to match PCB layout

firmware/src/controller/charging.cpp, firmware/src/controller/charging.h, firmware/src/controller/state_manager.cpp
=> Allow charging based on hardware switch

firmware/src/controller/charging.cpp, firmware/src/controller/display.cpp, firmware/src/controller/gpio.cpp, firmware/src/controller/gpio.h, firmware/src/controller/state_manager.cpp, firmware/src/controller/supplying.cpp, firmware/src/controller/supplying.h
Closes #46
Device charging working.
=> Add supplying functionality

firmware/src/controller/adc.cpp
=> Average adc readings

firmware/src/controller/charging.cpp, firmware/src/controller/charging.h, firmware/src/controller/state_manager.cpp
=> Add over current protection

firmware/src/controller/display.cpp
=> Add temperature readings to display

README.md, firmware/src/controller/charging.cpp, firmware/src/controller/charging.h, firmware/src/controller/controller.ino, firmware/src/controller/display.cpp, firmware/src/controller/encoder.cpp, firmware/src/controller/encoder.h, firmware/src/controller/gpio.cpp, firmware/src/controller/gpio.h, firmware/src/controller/interrupt.cpp, firmware/src/controller/interrupt.h, firmware/src/controller/menu.cpp, firmware/src/controller/menu.h, firmware/src/controller/mode.cpp, firmware/src/controller/mode.h, firmware/src/controller/state_manager.cpp, firmware/src/controller/supplying.cpp, firmware/src/controller/supplying.h
=> Implement encoder for mode switching via menu

firmware/src/controller/adc.cpp, firmware/src/controller/adc.h, firmware/src/controller/battery.cpp, firmware/src/controller/charging.cpp, firmware/src/controller/temperature.cpp
=> Update adc function names

firmware/src/controller/encoder.cpp
=> Debounce rotary encoder button presses

firmware/src/controller/display.cpp, firmware/src/controller/temperature.cpp, firmware/src/controller/temperature.h
- Closes #47
- Possible fix to #42 but it needs testing
=> Add thermistor readings to display

firmware/src/controller/battery.cpp, firmware/src/controller/battery.h, firmware/src/controller/charging.cpp, firmware/src/controller/charging.h, firmware/src/controller/state_manager.cpp
=> Add battery charge checks to prevent overcharging

firmware/src/controller/adc.cpp, firmware/src/controller/adc.h
=> Calibrate adc reference

firmware/src/controller/battery.cpp, firmware/src/controller/battery.h, firmware/src/controller/charging.cpp, firmware/src/controller/charging.h, firmware/src/controller/display.cpp, firmware/src/controller/state_manager.cpp
=> Add support for supply side power metrics

firmware/src/controller/battery.cpp, firmware/src/controller/battery.h, firmware/src/controller/controller.ino, firmware/src/controller/display.cpp
=> Show total battery charge as percentage

firmware/src/controller/battery.cpp, firmware/src/controller/battery.h, firmware/src/controller/display.cpp, firmware/src/controller/mode.h, firmware/src/controller/state_manager.cpp
=> Check battery voltage levels while discharging

firmware/src/controller/display.cpp
Fixes font issues, and uses less RAM.
=> Port display writing to u8g2

firmware/src/controller/charging.cpp, firmware/src/controller/charging.h, firmware/src/controller/display.cpp, firmware/src/controller/menu.cpp, firmware/src/controller/mode.h, firmware/src/controller/state_manager.cpp, firmware/test/state_manager_tests.cpp
=> Add support for simultaneous charging and supplying

firmware/src/controller/temperature.cpp
=> Fix resistance calculation for low-side thermistor

firmware/src/controller/display.cpp
=> Add supply metrics

firmware/src/controller/battery.cpp, firmware/src/controller/battery.h, firmware/src/controller/state_manager.cpp
=> Fix balancing mode exit condition
